### ISSUE TITLE
Ambiguity and questions

### ISSUE THREAD

**Issue by ArnoGrobler** [DillonHeins/Charlie#3]
- [x] Does the user always have to publish for a conference? Can you publish without having a conference?

- [x] What happens if a conference is cancelled? Does the paper remain in a unpublished state? 

- [x] If Conference is cancelled can you assign the paper to new conference?

- [x] For implementation, do we have to make a web server or is a server provided to us by the cs department.

- [x] Do all users have to belong to a research group?

- [x] Should the admin and HoD not be swapped in our diagram?
 
- [x] In our use case diagrams should a user not also be allowed to 1: logout, as well as 2: edit their profile?

- [x]  Should sending a deadline update notification to an author not be a use case of the system which is initiated by a user when editing a paper deadline?

**Comment by DillonHeins** [comment]
"Should the admin and HoD not be swapped in our diagram?"

If you are referring to the use case diagrams then I think you have viewed them incorrectly. The one user is a Head of Research (Not Head of Department). The admin user is the Head of Department.

**Comment by DillonHeins** [comment]
"Does the user always have to publish for a conference? Can you publish without having a conference?"

As far as I understand a user does not need to select a conference/journal for their paper when creating an entry but when they decide they want to publish it they must specify the means through which it is being published via editing their entry.

"What happens if a conference is cancelled? Does the paper remain in a unpublished state?"

To be honest I don't know what would happen in this case. Our system isn't connected to the Internet so we would have to manually let the system know a conference was cancelled. Perhaps user intervention is required in this case. If a conference is cancelled the user will edit their paper to have no conference until a solution has been established.

"If Conference is cancelled can you assign the paper to new conference?"

I do believe that you can edit a paper entry to change its conference/journal.


With regards to the above, I am not too sure if I am correct on these matters but this is my understanding. If anyone else could contribute their views so we can establish what is right and what is wrong. Thanks.

**Comment by u13054903** [comment]
"For implementation, do we have to make a web server or is a server provided to us by the cs department."

I think this topic will be further discussed in either the next phase or the actual implementation phase. We can add this as an open issue (section 6) .
