### ISSUE TITLE
Section 5.4 - Process Specification 

### ISSUE THREAD

**Issue by pris264** [DillonHeins/Charlie#4]
-  For which use cases must Keo and I create the process specifications? It's a bit unclear at the moment.

**Comment by pris264** [comment]
We need a clear list from the guys that wrote down all the possible use cases.

**Comment by pris264** [comment]
I need clarity on the registration process. How are the users registered? Is it the admin that adds users? If so, how are the passwords and usernames generated for login purposes?

**Comment by DillonHeins** [comment]
If you have a look at the use case diagrams you will see that it is the admin that registers users. There are no usernames. Emails are used to identify the user. We're allowed to design our own implementation for a lot of the functional requirements, I think it would be best if the user is emailed a one time password which they can login once with so that they can set their own password. Or we could email the user a link which allows them to set their own password, similar to how most websites authenticate users.

**Comment by pris264** [comment]
In the user subsystem section of the software document, shouldn't there be a logout and an edit profile option?
